// Bundles kb/*.pl into web/kb-bundle.js so index.html works when opened
// straight from disk (file:// blocks fetch). When the page IS served over
// http the app fetches the .pl files directly, so live edits show up
// without rebuilding. The .pl files remain the single source of truth.
const fs = require('fs');
const path = require('path');

const FILES = ['boss_kb.pl', 'boss_derive.pl', 'boss_rules.pl', 'boss_infer.pl', 'boss_advice.pl'];
const out = {};
for (const f of FILES) out[f] = fs.readFileSync(path.join(__dirname, 'kb', f), 'utf8');

fs.writeFileSync(
  path.join(__dirname, 'web', 'kb-bundle.js'),
  '// GENERATED by build.js - do not edit. Edit kb/*.pl and re-run: node build.js\n' +
  'window.BOSS_KB_FILES = ' + JSON.stringify(FILES) + ';\n' +
  'window.BOSS_KB = ' + JSON.stringify(out, null, 0) + ';\n'
);
// Also expose the six SRS section 12 validation cases as loadable examples.
const casesSrc = fs.readFileSync(path.join(__dirname, 'test', 'cases.pl'), 'utf8');
const re = /case\((\d+),\s*'([^']+)',\s*expected\((\w+),\s*(-?[\d.]+)\),\s*\[([\s\S]*?)\]\)\./g;
const cases = [];
let m;
while ((m = re.exec(casesSrc)) !== null) {
  const answers = {};
  for (const f of m[5].split(',').map(s => s.trim()).filter(Boolean)) {
    const g = /^(\w+)\((.+)\)$/.exec(f);
    if (!g) continue;
    const v = g[2].trim();
    answers[g[1]] = /^-?\d+(\.\d+)?$/.test(v) ? Number(v) : v;
  }
  cases.push({ id: +m[1], name: m[2], expect: m[3], cf: parseFloat(m[4]), answers });
}
fs.writeFileSync(
  path.join(__dirname, 'web', 'cases-bundle.js'),
  '// GENERATED by build.js from test/cases.pl - do not edit.\n' +
  'window.BOSS_CASES = ' + JSON.stringify(cases, null, 0) + ';\n'
);

console.log('web/kb-bundle.js written (' + FILES.length + ' files)');
console.log('web/cases-bundle.js written (' + cases.length + ' cases)');
